use hanabi_protocol::HanabiLiveReplay;

// Frozen from the original full Hanabi Live exports, not generated by the
// implementation under test. Protects every card position for all five seeds.
#[test]
fn seeded_decks_match_original_exports() {
    for (seed, expected) in [
        (
            "p4v0s415",
            "b1 r1 y2 g4 b4 p2 p2 g3 g1 r3 y5 r2 b2 y1 b2 b1 y3 r4 b3 p1 b3 y1 g2 r5 p5 y2 p1 b5 y3 y1 g2 y4 g4 p3 p4 r4 y4 r1 p3 g3 g1 b4 r3 r1 g5 p4 b1 r2 p1 g1",
        ),
        (
            "p4v0s9",
            "r2 b1 y4 g2 y3 r3 g1 y1 r1 p4 p1 b5 g1 r1 r3 b2 g2 p3 p1 p2 g4 g5 p1 p5 g1 y4 y2 y1 r4 r5 g3 r4 g3 y1 b3 y3 b3 b4 b2 b1 b1 p3 y5 r2 g4 p2 p4 y2 r1 b4",
        ),
        (
            "p4v0s2",
            "p3 b1 y4 g1 b4 y1 p4 g2 r4 p2 r1 p1 b5 r2 p1 g1 b2 r3 r1 p4 r4 p2 b3 g5 r3 y3 p1 y2 y4 y3 y1 p5 p3 b4 r5 b1 g4 b2 y5 g4 g3 y1 g2 g3 r1 b1 b3 y2 r2 g1",
        ),
        (
            "p4v0s3",
            "p3 r3 y4 r4 y1 y1 y3 g4 y5 r2 p4 g2 p2 y2 p3 y4 p4 b3 p2 g1 p1 b5 b4 g3 y1 g3 g4 p1 r1 r1 b2 y3 b1 g1 b1 b4 y2 p5 r2 b3 g1 b2 r1 p1 r3 r5 g5 b1 g2 r4",
        ),
        (
            "p4v0s1",
            "y4 y1 y4 b3 b1 p4 b2 p1 y1 p1 g4 b4 p4 r3 p3 y2 r3 b5 r2 g5 g1 r1 p5 r1 p2 g2 r2 y5 r4 y2 p3 b2 p2 r5 g1 p1 b4 b1 r4 y1 r1 g4 y3 y3 g3 g1 b3 b1 g3 g2",
        ),
    ] {
        let json =
            serde_json::json!({"players": ["A", "B", "C", "D"], "seed": seed, "actions": []});
        let replay = HanabiLiveReplay::from_json(&json.to_string()).unwrap();
        let actual = replay
            .deck
            .iter()
            .map(|card| {
                format!(
                    "{}{}",
                    char::from(b"rygbp"[usize::from(card.suit_index)]),
                    card.rank
                )
            })
            .collect::<Vec<_>>()
            .join(" ");
        assert_eq!(actual, expected, "{seed}");
        replay.state_at_turn(0).unwrap();
    }
}

#[test]
fn explicit_deck_takes_precedence_over_seed_metadata() {
    let json = serde_json::json!({"players": ["A", "B"], "seed": "untrusted metadata",
        "deck": [{"suitIndex": 0, "rank": 5}], "actions": []});
    let replay = HanabiLiveReplay::from_json(&json.to_string()).unwrap();
    assert_eq!(replay.deck.len(), 1);
    assert_eq!(replay.deck[0].rank, 5);
    // An explicitly empty/invalid deck must not silently become a seeded one.
    assert!(replay.state_at_turn(0).is_err());
    let empty =
        serde_json::json!({"players": ["A", "B"], "seed": "p2v0s1", "deck": [], "actions": []});
    let replay = HanabiLiveReplay::from_json(&empty.to_string()).unwrap();
    assert!(replay.deck.is_empty());
    assert!(replay.state_at_turn(0).is_err());
}

#[test]
fn canonical_seeds_support_all_standard_player_counts() {
    for count in 2..=5 {
        let players = (0..count)
            .map(|i| format!("Player {i}"))
            .collect::<Vec<_>>();
        let json =
            serde_json::json!({"players": players, "seed": format!("p{count}v0s0"), "actions": []});
        let replay = HanabiLiveReplay::from_json(&json.to_string()).unwrap();
        assert_eq!(replay.deck.len(), 50);
        replay.state_at_turn(0).unwrap();
        assert_eq!(
            replay,
            HanabiLiveReplay::from_json(&json.to_string()).unwrap()
        );
    }
}

#[test]
fn seed_only_replays_reject_invalid_or_inconsistent_setup() {
    for seed in ["", "p4v1s1", "p3v0s1", "p4v0s", "p4v0s1x", "not-a-seed"] {
        let json =
            serde_json::json!({"players": ["A", "B", "C", "D"], "seed": seed, "actions": []});
        assert!(
            HanabiLiveReplay::from_json(&json.to_string()).is_err(),
            "{seed}"
        );
    }
    for json in [
        serde_json::json!({"players": ["A", "B"], "actions": []}),
        serde_json::json!({"players": ["A", "B"], "seed": "p2v0s1", "actions": [], "options": {"variant": "Rainbow"}}),
    ] {
        assert!(HanabiLiveReplay::from_json(&json.to_string()).is_err());
    }
}
